const APP_CONSTANT = {
  NAME: 'Name',
  ENTER_NAME: 'Enter Name',
  MIDDAL_NAME: 'Middal Name',
  ENTER_MIDDAL_NAME: 'Enter Middal Name',
  SURENAME: 'Surname',
  ENTER_SURENAME: 'Enter Surname',
  EMAIL: 'Email',
  ENTER_EMAIL: 'Enter Email',
  MOBILE_NO: 'Mobile No.',
  ENTER_MOBILE_NO: '+91 987654321',
  DOB: 'Date of Birth ',
  CREATE_ACCOUNT: 'Create Account',
  MALE: 'Male',
  FEMALE: 'Female',
  OFFICE_ADDRESS: 'Office Address',
  ENTER_OFFICE_ADDRESS: 'Please Select Your Office Address',
  REMARKS: 'Remarks',
  PLEASE_ENTER_REMARKS: 'Please Enter Remarks',
  CURRENT: 'Current',
  RETIRED: 'Retired',
};

const ASYNC_KEY = {
  AUTH: 'AUTH',
};

const GENDER = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
};

const STATUS = {
  CURRENT: 'CURRENT',
  RETIRED: 'RETIRED',
};

const MODAL_TYPE = {
  DESIGNATION: 'DESIGNATION',
  OFFICE_DISTRICT: 'OFFICE_DISTRICT',
  NATIVE_DISTRICT: 'NATIVE_DISTRICT',
};

const DESTRICT = [
  'Ahmedabad',
  'Amreli',
  'Anand',
  'Arvalli',
  'Banaskantha',
  'Bharuch',
  'Bhavnagar ',
  'Botad',
  'Chhota Udaipur',
  'Dahod ',
  'Dang',
  'Devbhoomi Dwarka',
  'Gandhinagar ',
  'Gir Somnath ',
  'Jamnagar ',
  'Junagadh',
  'Kutch',
  'Kheda',
  'Mahisagar',
  'Mehsana',
  'Morbi',
  'Narmada',
  'Navsari',
  'Panchmahal',
  'Patan',
  'Porbandar',
  'Rajkot',
  'Sabarkantha',
  'Surat',
  'Surendranagar ',
  'Tapi',
  'Vadodara',
  'Valsad',
];

const DESIGNATION = [
  { title: 'Peon' },
  { title: 'Junior Clerk' },
  { title: 'Senior Clerk' },
  { title: 'Head Clerk' },
  { title: 'Office Supritendent ' },
  { title: 'Agriculture Assistant ' },
  { title: 'Horticulture Assistant ' },
  { title: 'Veterinary Assistant ' },
  { title: 'Assistant Supritendent of Fisheries ' },
  { title: 'Agriculture Supervisor' },
  { title: 'Horticulture Supervisor ' },
  { title: 'Veterinary Supervisor ' },
  { title: 'Supritendent of Fisheries' },
  { title: 'Agriculture Officer' },
  { title: 'Horticulture Officer' },
  { title: 'Veterinary Officer ' },
  { title: 'Fisheries Officer' },
  { title: 'Assistant Director of Agriculture ' },
  { title: 'Assistant Director of Horticulture ' },
  { title: 'Assistant Director of Animal Husbandry ' },
  { title: 'Assistant Director of Fisheries ' },
  { title: 'Deputy Director of Agriculture ' },
  { title: 'Deputy Director of Horticulture ' },
  { title: 'Deputy Director of Animal Husbandry ' },
  { title: 'Deputy Director of Fisheries' },
  { title: 'Joint Director of Agriculture' },
  { title: 'Joint Director of Horticulture' },
  { title: 'Joint Director of Animal Husbandry ' },
  { title: 'Joint Director of Fisheries ' },
  { title: 'Director of Agriculture ' },
  { title: 'Director of Horticulture ' },
  { title: 'Director of Animal Husbandry ' },
  { title: 'Deputy Commissioner of Fisheries ' },
  { title: 'Commissioner of Fisheries ' },
  { title: 'Senior Technical Officer ' },
  { title: 'Senior Research Assistant ' },
  { title: 'Technical Assistant ' },
  { title: 'Farm Manager ' },
  { title: 'Assistant Professor' },
  { title: 'Associate Professor ' },
  { title: 'Professor' },
  { title: 'Professor and Head' },
  { title: 'Comptroller ' },
  { title: 'Assistant Registrar ' },
  { title: 'Registrar ' },
  { title: 'Associate Director of Research ' },
  { title: 'Director of Research ' },
  { title: 'Vice Chancellor' },
  { title: 'Gram Sevak' },
  { title: 'Talati' },
  { title: 'Extension Officer (Agri)' },

  { title: 'Deputy Section Officer' },
  { title: 'Section Officer' },
  { title: 'Deputy Secretary ' },
  { title: 'Joint Secretary ' },
  { title: 'Additional Secretary ' },
  { title: 'Assistant Research Scientist ' },
  { title: 'Associate Research Scientist ' },
  { title: 'Research Scientist ' },
  { title: 'Live Stock Inspector ' },
  { title: 'Garden Supervisor ' },
  { title: 'Director of IT' },
  { title: 'SMS (Subject Matter Specialist)' },
  { title: 'Scientist ' },
  { title: 'Senior Scientist ' },
  { title: 'Senior Scientist and Head' },
  { title: 'Seed Officer ' },
  { title: 'Senior Seed officer ' },
  { title: 'District Agriculture Officer ' },
  { title: 'Additional Director of Agriculture ' },
  { title: 'Additional Director of Horticulture ' },
  { title: 'Agriculture Engineer' },
  { title: 'Principal ' },
  { title: 'Principal and Dean' },
  { title: 'Principal Scientist ' },
  { title: 'Principal Scientist and Head ' },
  { title: 'National Professor ' },
  { title: 'Private Secretary ' },
  { title: 'Director of Extension Education ' },
  { title: 'Director of Students`s Welfare ' },
  { title: 'Branch Manager ' },
];

export {
  APP_CONSTANT,
  ASYNC_KEY,
  GENDER,
  STATUS,
  MODAL_TYPE,
  DESTRICT,
  DESIGNATION,
};
