const APP_CONSTANT = {
  NAME: 'Name',
  ENTER_NAME: 'Enter Name',
  MIDDAL_NAME: 'Middal Name',
  ENTER_MIDDAL_NAME: 'Enter Middal Name',
  SURENAME: 'Surname',
  ENTER_SURENAME: 'Enter Surname',
  EMAIL: 'Email',
  ENTER_EMAIL: 'Enter Email',
  MOBILE_NO: 'Mobile No.',
  ENTER_MOBILE_NO: '9876543210',
  DOB: 'Date of Birth ',
  CREATE_ACCOUNT: 'Create Account',
  MALE: 'Male',
  FEMALE: 'Female',
  OFFICE_ADDRESS: 'Office Address',
  ENTER_OFFICE_ADDRESS: 'Please Enter Your Office Address',
  REFERENCE_BY: 'Reference By',
  REMARKS: 'Remarks',
  PLEASE_ENTER_NATIVE_DISTRICT: 'Please Enter Native District',
  PLEASE_ENTER_YOUR_SPECELIZATION: 'Please Enter Your Specelization',
  PLEASE_ENTER_REMARKS: 'Please Enter Remarks',
  CURRENT: 'Current',
  RETIRED: 'Retired',
  VRS: 'VRS',
  DISTRICT: 'District',
  DESIGNATION: 'Designation',
  DESIGNATION_PLACEHOLDER: 'Please Select Your Designation*',
  OFFICE_DISTRICT: 'Office District',
  OFFICE_DISTRICT_PLACEHOLDER: 'Please Select Office District *',
  NATIVE_DISTRICT: 'Native District',
  NATIVE_DISTRICT_PLACEHOLDER: 'Please Select Native District*',
  PREFIX: 'Prefix',
  JOB_STATUS: 'Job Status',
  CLOSE: 'Close',
  PROFILE: 'Profile',
  SEARCH: 'Search',
  GENDER: 'Gender',
  MARITAL_STATUS: 'Marital Status',
  MARRIED: 'Married',
  UN_MARRIED: 'Unmarried',
  WIDOW: 'Widow',
  DR: 'Dr.',
  MR: 'Mr.',
  MS: 'Ms.',
  MISS: 'Miss',
  UPLOAD_OFFICE_ID: 'Upload Office ID',
  UPLOAD_LEAVING_CERTI: 'Upload Leaving Certificate',
  CLASS: 'Class',
  ONE: 'I',
  TWO: 'II',
  THREE: 'III',
  FOUR: 'IV',
  NATIVE_DISTRICT_ADDRESS: 'Native District Address',
  SPECELIZATOIN: 'Specelization',
  ERROR: 'Error',
  WARNING: 'Warning',
  REGISTRATION: 'Registration',
};

const ASYNC_KEY = {
  AUTH: 'AUTH',
};

const GENDER = {
  MALE: 'Male',
  FEMALE: 'Female',
};

const USER_PREFIX = {
  DR: 'Dr',
  MR: 'Mr',
  MS: 'Ms',
  MISS: 'Miss',
};
const STATUS = {
  CURRENT: 'Current',
  RETIRED: 'Retired',
  VRS: 'VRS',
};
const MARITAL_STATUS = {
  MARRIED: 'Married',
  UN_MARRIED: 'Unmarried',
  WIDOW: 'Widow',
};

const OFFICER_CLASS = {
  ONE: 'I',
  TWO: 'II',
  THREE: 'III',
  FOUR: 'IV',
};

const MODAL_TYPE = {
  DESIGNATION: 'DESIGNATION',
  OFFICE_DISTRICT: 'OFFICE_DISTRICT',
  NATIVE_DISTRICT: 'NATIVE_DISTRICT',
};

const DISTRICT = [
  { title: 'Ahmedabad' },
  { title: 'Amreli' },
  { title: 'Anand' },
  { title: 'Arvalli' },
  { title: 'Banaskantha' },
  { title: 'Bharuch' },
  { title: 'Bhavnagar ' },
  { title: 'Botad' },
  { title: 'Chhota Udaipur' },
  { title: 'Dahod ' },
  { title: 'Dang' },
  { title: 'Devbhoomi Dwarka' },
  { title: 'Gandhinagar ' },
  { title: 'Gir Somnath ' },
  { title: 'Jamnagar ' },
  { title: 'Junagadh' },
  { title: 'Kutch' },
  { title: 'Kheda' },
  { title: 'Mahisagar' },
  { title: 'Mehsana' },
  { title: 'Morbi' },
  { title: 'Narmada' },
  { title: 'Navsari' },
  { title: 'Panchmahal' },
  { title: 'Patan' },
  { title: 'Porbandar' },
  { title: 'Rajkot' },
  { title: 'Sabarkantha' },
  { title: 'Surat' },
  { title: 'Surendranagar ' },
  { title: 'Tapi' },
  { title: 'Vadodara' },
  { title: 'Valsad' },
];

const DESIGNATION = [
  { title: 'Peon' },
  { title: 'Junior Clerk' },
  { title: 'Senior Clerk' },
  { title: 'Head Clerk' },
  { title: 'Office Supritendent ' },
  { title: 'Agriculture Assistant ' },
  { title: 'Horticulture Assistant ' },
  { title: 'Veterinary Assistant ' },
  { title: 'Assistant Supritendent of Fisheries ' },
  { title: 'Agriculture Supervisor' },
  { title: 'Horticulture Supervisor ' },
  { title: 'Veterinary Supervisor ' },
  { title: 'Supritendent of Fisheries' },
  { title: 'Agriculture Officer' },
  { title: 'Horticulture Officer' },
  { title: 'Veterinary Officer ' },
  { title: 'Fisheries Officer' },
  { title: 'Assistant Director of Agriculture ' },
  { title: 'Assistant Director of Horticulture ' },
  { title: 'Assistant Director of Animal Husbandry ' },
  { title: 'Assistant Director of Fisheries ' },
  { title: 'Deputy Director of Agriculture ' },
  { title: 'Deputy Director of Horticulture ' },
  { title: 'Deputy Director of Animal Husbandry ' },
  { title: 'Deputy Director of Fisheries' },
  { title: 'Joint Director of Agriculture' },
  { title: 'Joint Director of Horticulture' },
  { title: 'Joint Director of Animal Husbandry ' },
  { title: 'Joint Director of Fisheries ' },
  { title: 'Director of Agriculture ' },
  { title: 'Director of Horticulture ' },
  { title: 'Director of Animal Husbandry ' },
  { title: 'Deputy Commissioner of Fisheries ' },
  { title: 'Commissioner of Fisheries ' },
  { title: 'Senior Technical Officer ' },
  { title: 'Senior Research Assistant ' },
  { title: 'Technical Assistant ' },
  { title: 'Farm Manager ' },
  { title: 'Assistant Professor' },
  { title: 'Associate Professor ' },
  { title: 'Professor' },
  { title: 'Professor and Head' },
  { title: 'Comptroller ' },
  { title: 'Assistant Registrar ' },
  { title: 'Registrar ' },
  { title: 'Associate Director of Research ' },
  { title: 'Director of Research ' },
  { title: 'Vice Chancellor' },
  { title: 'Gram Sevak' },
  { title: 'Talati' },
  { title: 'Extension Officer (Agri)' },

  { title: 'Deputy Section Officer' },
  { title: 'Section Officer' },
  { title: 'Deputy Secretary ' },
  { title: 'Joint Secretary ' },
  { title: 'Additional Secretary ' },
  { title: 'Assistant Research Scientist ' },
  { title: 'Associate Research Scientist ' },
  { title: 'Research Scientist ' },
  { title: 'Live Stock Inspector ' },
  { title: 'Garden Supervisor ' },
  { title: 'Director of IT' },
  { title: 'SMS (Subject Matter Specialist)' },
  { title: 'Scientist ' },
  { title: 'Senior Scientist ' },
  { title: 'Senior Scientist and Head' },
  { title: 'Seed Officer ' },
  { title: 'Senior Seed officer ' },
  { title: 'District Agriculture Officer ' },
  { title: 'Additional Director of Agriculture ' },
  { title: 'Additional Director of Horticulture ' },
  { title: 'Agriculture Engineer' },
  { title: 'Principal ' },
  { title: 'Principal and Dean' },
  { title: 'Principal Scientist ' },
  { title: 'Principal Scientist and Head ' },
  { title: 'National Professor ' },
  { title: 'Private Secretary ' },
  { title: 'Director of Extension Education ' },
  { title: 'Director of Students`s Welfare ' },
  { title: 'Branch Manager ' },
];

const ERROR = {
  PLEASE_ENTER_NAME: 'Please Enter name',
  PLEASE_ENTER_MIDDAL_NAME: 'Enter Middal Name',
  PLEASE_ENTER_SURE_NAME: 'Enter SureName',
  PLEASE_ENTER_PHONE_NUMBER: 'Enter Phone Number',
  PLEASE_ENTER_VALID_PHONE_NUMBER: 'Please Enter Valid Phone Number',
  PLEASE_ENTER_OFFICE_ADDRESS: 'Please Enter OfficeAddress',
  PLEASE_SELECT_YOUR_DESIGNATION: 'Please Select Your Designation',
  PLEASE_SELECT_YOUR_OFFICE_ADDREDSS: 'Please Select Your Office Address',
  PLEASE_SELECT_YOUR_NATIVE_DISTRICT: 'Please Select Your Native District',
  SOME_THING_WRONG: 'SomeThing Went Wrong',
};

export {
  APP_CONSTANT,
  ASYNC_KEY,
  GENDER,
  STATUS,
  MODAL_TYPE,
  DISTRICT,
  DESIGNATION,
  USER_PREFIX,
  MARITAL_STATUS,
  OFFICER_CLASS,
  ERROR,
};
